"""Add household inventory, leftovers, and reproducible experiment runs.

Revision ID: 20260731_0002
Revises: 20260731_0001
Create Date: 2026-07-31
"""
from __future__ import annotations
from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op
revision: str = "20260731_0002"
down_revision: Union[str, None] = "20260731_0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def _tables()->set[str]: return set(sa.inspect(op.get_bind()).get_table_names())
def _indexes(table_name:str)->set[str]: return {value["name"] for value in sa.inspect(op.get_bind()).get_indexes(table_name)}
def _ensure_index(table:str,name:str,columns:list[str])->None:
    if name not in _indexes(table): op.create_index(name,table,columns)
def upgrade()->None:
    if "households" not in _tables():
        op.create_table("households",sa.Column("id",sa.String(),nullable=False),sa.Column("owner_user_id",sa.String(),nullable=False),sa.Column("name",sa.String(),nullable=False),sa.Column("timezone",sa.String(),nullable=False,server_default="UTC"),sa.Column("version",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.ForeignKeyConstraint(["owner_user_id"],["users.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"))
    _ensure_index("households","ix_households_owner_user_id",["owner_user_id"])
    if "household_members" not in _tables():
        op.create_table("household_members",sa.Column("id",sa.Integer(),autoincrement=True,nullable=False),sa.Column("household_id",sa.String(),nullable=False),sa.Column("display_name",sa.String(),nullable=False),sa.Column("linked_user_id",sa.String(),nullable=True),sa.Column("servings_multiplier",sa.Float(),nullable=False,server_default="1"),sa.Column("allergies",sa.JSON(),nullable=False),sa.Column("dietary_restrictions",sa.JSON(),nullable=False),sa.Column("disliked_ingredients",sa.JSON(),nullable=False),sa.Column("active",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.ForeignKeyConstraint(["household_id"],["households.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["linked_user_id"],["users.id"],ondelete="SET NULL"),sa.PrimaryKeyConstraint("id"))
    _ensure_index("household_members","ix_household_members_household_id",["household_id"]); _ensure_index("household_members","ix_household_members_linked_user_id",["linked_user_id"])
    if "pantry_items" not in _tables():
        op.create_table("pantry_items",sa.Column("id",sa.Integer(),autoincrement=True,nullable=False),sa.Column("household_id",sa.String(),nullable=False),sa.Column("canonical_name",sa.String(),nullable=False),sa.Column("display_name",sa.String(),nullable=False),sa.Column("quantity_min",sa.Float(),nullable=False),sa.Column("quantity_max",sa.Float(),nullable=False),sa.Column("unit",sa.String(),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=True),sa.Column("opened_at",sa.DateTime(timezone=True),nullable=True),sa.Column("source",sa.String(),nullable=False,server_default="manual"),sa.Column("item_metadata",sa.JSON(),nullable=False),sa.Column("version",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.CheckConstraint("quantity_min >= 0",name="ck_pantry_quantity_min_nonnegative"),sa.CheckConstraint("quantity_max >= quantity_min",name="ck_pantry_quantity_range"),sa.ForeignKeyConstraint(["household_id"],["households.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"))
    for name,columns in (("ix_pantry_items_household_id",["household_id"]),("ix_pantry_items_canonical_name",["canonical_name"]),("ix_pantry_items_expires_at",["expires_at"])): _ensure_index("pantry_items",name,columns)
    if "leftover_batches" not in _tables():
        op.create_table("leftover_batches",sa.Column("id",sa.Integer(),autoincrement=True,nullable=False),sa.Column("household_id",sa.String(),nullable=False),sa.Column("recipe_id",sa.String(),nullable=False),sa.Column("source_plan_id",sa.Integer(),nullable=True),sa.Column("portions_available",sa.Float(),nullable=False),sa.Column("cooked_at",sa.DateTime(timezone=True),nullable=False),sa.Column("expires_at",sa.DateTime(timezone=True),nullable=True),sa.Column("frozen",sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column("notes",sa.String(),nullable=True),sa.Column("version",sa.Integer(),nullable=False,server_default="1"),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.CheckConstraint("portions_available >= 0",name="ck_leftovers_nonnegative"),sa.ForeignKeyConstraint(["household_id"],["households.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["recipe_id"],["recipes.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["source_plan_id"],["meal_plans.id"],ondelete="SET NULL"),sa.PrimaryKeyConstraint("id"))
    for name,columns in (("ix_leftover_batches_household_id",["household_id"]),("ix_leftover_batches_recipe_id",["recipe_id"]),("ix_leftover_batches_expires_at",["expires_at"])): _ensure_index("leftover_batches",name,columns)
    if "inventory_events" not in _tables():
        op.create_table("inventory_events",sa.Column("id",sa.Integer(),autoincrement=True,nullable=False),sa.Column("household_id",sa.String(),nullable=False),sa.Column("pantry_item_id",sa.Integer(),nullable=True),sa.Column("leftover_id",sa.Integer(),nullable=True),sa.Column("event_type",sa.String(),nullable=False),sa.Column("quantity_min",sa.Float(),nullable=False),sa.Column("quantity_max",sa.Float(),nullable=False),sa.Column("unit",sa.String(),nullable=False),sa.Column("reason",sa.String(),nullable=True),sa.Column("event_metadata",sa.JSON(),nullable=False),sa.Column("idempotency_key",sa.String(),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.CheckConstraint("quantity_min >= 0",name="ck_inventory_event_min_nonnegative"),sa.CheckConstraint("quantity_max >= quantity_min",name="ck_inventory_event_quantity_range"),sa.ForeignKeyConstraint(["household_id"],["households.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["pantry_item_id"],["pantry_items.id"],ondelete="SET NULL"),sa.ForeignKeyConstraint(["leftover_id"],["leftover_batches.id"],ondelete="SET NULL"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("household_id","idempotency_key",name="uq_inventory_event_idempotency"))
    for name,columns in (("ix_inventory_events_household_id",["household_id"]),("ix_inventory_events_pantry_item_id",["pantry_item_id"]),("ix_inventory_events_leftover_id",["leftover_id"]),("ix_inventory_events_event_type",["event_type"]),("ix_inventory_events_created_at",["created_at"])): _ensure_index("inventory_events",name,columns)
    if "experiment_runs" not in _tables():
        op.create_table("experiment_runs",sa.Column("id",sa.String(),nullable=False),sa.Column("user_id",sa.String(),nullable=True),sa.Column("experiment_id",sa.String(),nullable=False),sa.Column("status",sa.String(),nullable=False),sa.Column("seed",sa.Integer(),nullable=False),sa.Column("config",sa.JSON(),nullable=False),sa.Column("metrics",sa.JSON(),nullable=False),sa.Column("artifact_manifest",sa.JSON(),nullable=False),sa.Column("dataset_fingerprint",sa.String(),nullable=True),sa.Column("model_fingerprint",sa.String(),nullable=True),sa.Column("error_message",sa.String(),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False,server_default=sa.func.now()),sa.Column("started_at",sa.DateTime(timezone=True),nullable=True),sa.Column("completed_at",sa.DateTime(timezone=True),nullable=True),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="SET NULL"),sa.PrimaryKeyConstraint("id"))
    for name,columns in (("ix_experiment_runs_user_id",["user_id"]),("ix_experiment_runs_experiment_id",["experiment_id"]),("ix_experiment_runs_status",["status"]),("ix_experiment_runs_dataset_fingerprint",["dataset_fingerprint"]),("ix_experiment_runs_model_fingerprint",["model_fingerprint"]),("ix_experiment_runs_created_at",["created_at"])): _ensure_index("experiment_runs",name,columns)
def downgrade()->None:
    tables=_tables()
    for table in ("experiment_runs","inventory_events","leftover_batches","pantry_items","household_members","households"):
        if table in tables: op.drop_table(table); tables.remove(table)
